### PR TITLE
Config methods for timestamps

### PR DESCRIPTION
**Pull request by rebecca-eakins**
Hey there! In working with @subvertallchris at our day job, we realized one should be able to configure default timestamps globally from the config file. This PR makes it happen.

There are actually very few changes, since `DeclaredProperty#register_magic_property` already has a bit of timestamp-y logic. The default action is as it was before; timestamps will be `DateTime` unless told otherwise.

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
This is great, thanks!

What do you think about the idea of having a configuration variable to enable `created_at` / `updated_at` properties on all models?  I honestly feel like this should be the default (though it would be a 6.0.0 change, if so).  It might be good to have a method which disables timestamps as well, if this was implemented.

**Comment by rebecca-eakins** [comment]
That's such great feedback! I'll get cracking on these points this weekend and add it to the PR.

Just note, I'm traveling for family reasons so I might not be able to submit until Sunday evening. 

Thank you for your thoughts!

**Comment by cheerfulstoic** [comment]
Awesome, thanks!  And no rush, certainly!

**Comment by rebecca-eakins** [comment]
Hi @cheerfulstoic! Since I ended up adding new functionality, I'm going to close this PR and open a new one comparing against master.

**Pull request closed without merging**
