### PR TITLE
Eager loading

### PR DESCRIPTION
**Pull request by cheerfulstoic**
It's loading!  It's eager!  OMG!!!1

### CODE REVIEW

**Comment by dpisarewski** [comment]
The most-wanted feature, imho )

**Comment by cheerfulstoic** [comment]
Agreed, though @subvertallchris is doing some performance improvements that I think will be welcomed by all as well ;)

As for a status update on this, I've got a final bit I'm trying to do which should allow eager loading to go as deep and you want.  After that I need to finish up the documentation and I'll merge.

**Comment by subvertallchris** [comment]
:fireworks:

**Comment by cheerfulstoic** [comment]
Finally, here's some eager loading for y'all!

**Pull request merged**
