### PR TITLE
QueryFactory w/RelatedNode

### PR DESCRIPTION
**Pull request by subvertallchris**
Same idea as https://github.com/neo4jrb/neo4j/pull/1109 but implemented differently.

This fixes/permits:

```
MyRelClass.create(activerel_object.from_node, activerel_object.to_node)
```

### CODE REVIEW

**Comment by subvertallchris** [comment]
@djvs

**Comment by subvertallchris** [comment]
@cheerfulstoic I'm going to cherry-pick this into 6.1.x once it passes, too.

**Comment by cheerfulstoic** [comment]
Awesome ;)  Run-ran the one build because it looked like a transient error

**Comment by subvertallchris** [comment]
Then it happened again. Ugh. Let's start opening issues when we see these, then someone can take care of them when they have time.

**Comment by cheerfulstoic** [comment]
Transient(-ish) error fixed!

**Pull request merged**
