### PR TITLE
RelatedNode / Rel saving issues fix and test

### PR DESCRIPTION
**Pull request by djvs**
Update on https://github.com/neo4jrb/neo4j/pull/1108

### CODE REVIEW

**Comment by djvs** [comment]
-_-

**Comment by subvertallchris** [comment]
Three things:

You'll need to run `rubocop -a` on it and either fix or let it autocorrect issues it finds.
That particular spec file isn't actually run, hence the `_bad` in the name. We need to remove that file, so you'll probably want to move that test elsewhere.
Can you rename those commits to be descriptive? You can also `rebase -i` and squash them down to one commit.

Sorry to be a pain :-X. I'm happy to help with it from here, too.

**Comment by djvs** [comment]
Maybe you could do those last bits?  If you don't mind.  I'm out of my territory here.

**Comment by subvertallchris** [comment]
Sure, no problem. I'll ping you on it once it's done so you can check it out.

**Comment by cheerfulstoic** [comment]
We're all out of our territory until we're not ;)

Thanks so much!

**Comment by subvertallchris** [comment]
Merged in #1112 so I'm gonna close this, but thanks for getting it going!

**Pull request closed without merging**
