### PR TITLE
Return cached result for has_one relationships

### PR DESCRIPTION
**Pull request by jacobwgillespie**
We'll see if Travis tests pass - ideally I'd like to add a test to check if cached results are used, but I haven't figured out the test setup yet.

Before this PR:

```ruby
b = Book.find(book_id)
b.author # queries the database
b.author # queries the database again
```

After this PR:

```ruby
b = Book.find(book_id)
b.author # queries the database
b.author # returns the cached copy of the author

b.reload # reloads the book from the database
b.author # queries the database
b.author # returns the cached copy of the author
```

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
This is great, thanks!

If you look at `asociation_proxy_spec.rb` you'll see that there is a `expect_queries` helper method.  That's defined in the `spec_helper` which uses a `$expect_queries_count` global variable.  Not great certainly, but only used in the specs (and it's used to track a global count of queries, so maybe not the worst usage).

Anyway, you could use that to make the spec(s) if you want.  If that's good them I'm happy to bring this into the `5.1.x` branch and release a patch

**Comment by cheerfulstoic** [comment]
(oh, and `association_proxy_spec` isn't the best name anymore because association proxies aren't always used there.  For later refactoring ;)

**Comment by jacobwgillespie** [comment]
Sweet, added!  That was fairly painless :)

**Comment by jacobwgillespie** [comment]
They're failing, but it looks like it's not related to the added tests...

**Comment by cheerfulstoic** [comment]
Ah, fiddly-widdly-timey-wimey issues.  That's happened before.  I'll try to fix it for good now

**Comment by cheerfulstoic** [comment]
Ah, interesting.  So there was one timey-wimey issue, but it looks like the JRuby specs are failing because in `./spec/e2e/has_one_spec.rb:63` there were 3 queries expected but only 2 happened.  That seems more related to your change

**Comment by cheerfulstoic** [comment]
Weird... that line has nothing to do with `expect_queries`....  I've tried running it locally with JRuby with no issues...

**Comment by cheerfulstoic** [comment]
I've got to head out for the night, but I tried re-running the builds and they're still failing, so it's reproducible on Travis, at least.  I won't be around tomorrow but I'll take a look again soon.  You're welcome to figure it out as well, of course

**Comment by jacobwgillespie** [comment]
It's passing!  Realized I accidentally had the `b.reload` in the `expect_queries` - was testing the wrong thing.  :)  It was failing on my local machine too under jruby, but this fixes everywhere.  Thanks for the help!

**Comment by cheerfulstoic** [comment]
Awesome!  Thanks!  I'll merge and cut a patch shortly

**Comment by jacobwgillespie** [comment]
Thank you!  :cake:

**Comment by cheerfulstoic** [comment]
Released as 5.1.3.  Thanks again!

**Comment by cheerfulstoic** [comment]
Thanks coveralls... :-/

**Pull request merged**
