### PR TITLE
Add missing require statement for cypher session

### LINKED ISSUE #999: Tests on master  aren't passing for me
Currently on the commit `8ed91ca753abc53045bc57ad606527ed45446a45`.

I was getting the following error when running `bundle exec rspec spec/`:

>        uninitialized constant Neo4j::Core::CypherSession

I had to add the proper require:
```
diff --git a/lib/neo4j.rb b/lib/neo4j.rb
index 4db958b..0745fc7 100644
--- a/lib/neo4j.rb
+++ b/lib/neo4j.rb
@@ -11,6 +11,7 @@ require 'neo4j/version'

 require 'neo4j-core'
 require 'neo4j/core/query'
+require 'neo4j/core/cypher_session'
 require 'active_model'
 require 'active_support/concern'
 require 'active_support/core_ext/class/attribute.rb'
```

And now I'm down to 4 failing tests:
```
  1) Neo4j::ActiveNode::IdProperty id_property :my_id, on: :foobar throws exception if the same uuid is generated when saving node
     Failure/Error: expect { Clazz.create }.to raise_error(/Node \d+ already exists with label/)
       expected Exception with message matching /Node \d+ already exists with label/, got #<Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/3995, 404> with backtrace:
         # ./lib/neo4j/shared/callbacks.rb:39:in `create_model'
         # ./lib/neo4j/shared/persistence.rb:64:in `create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
         # ./lib/neo4j/active_node/persistence.rb:28:in `block in save'
         # ./lib/neo4j/active_node/persistence.rb:90:in `block in cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:89:in `cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:26:in `save'
         # ./lib/neo4j/shared/validations.rb:18:in `save'
         # ./lib/neo4j/active_node/persistence.rb:103:in `block in create'
         # ./lib/neo4j/active_node/persistence.rb:101:in `tap'
         # ./lib/neo4j/active_node/persistence.rb:101:in `create'
         # ./spec/e2e/id_property_spec.rb:189:in `block (4 levels) in <top (required)>'
         # ./spec/e2e/id_property_spec.rb:189:in `block (3 levels) in <top (required)>'
     # ./spec/e2e/id_property_spec.rb:189:in `block (3 levels) in <top (required)>'

  2) Neo4j::ActiveNode::IdProperty id_property :my_uuid, auto: :uuid throws exception if the same uuid is generated when saving node
     Failure/Error: expect { Clazz.create }.to raise_error(/Node \d+ already exists with label/)
       expected Exception with message matching /Node \d+ already exists with label/, got #<Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/4000, 404> with backtrace:
         # ./lib/neo4j/shared/callbacks.rb:39:in `create_model'
         # ./lib/neo4j/shared/persistence.rb:64:in `create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
         # ./lib/neo4j/active_node/persistence.rb:28:in `block in save'
         # ./lib/neo4j/active_node/persistence.rb:90:in `block in cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:89:in `cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:26:in `save'
         # ./lib/neo4j/shared/validations.rb:18:in `save'
         # ./lib/neo4j/active_node/persistence.rb:103:in `block in create'
         # ./lib/neo4j/active_node/persistence.rb:101:in `tap'
         # ./lib/neo4j/active_node/persistence.rb:101:in `create'
         # ./spec/e2e/id_property_spec.rb:305:in `block (4 levels) in <top (required)>'
         # ./spec/e2e/id_property_spec.rb:305:in `block (3 levels) in <top (required)>'
     # ./spec/e2e/id_property_spec.rb:305:in `block (3 levels) in <top (required)>'

  3) Neo4j::ActiveNode constraint constraint :name, type: :unique can not create two nodes with unique properties
     Failure/Error: expect { clazz_with_constraint.create(name: 'foobar') }.to raise_error StandardError, /already exists/
       expected StandardError with message matching /already exists/, got #<Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/4032, 404> with backtrace:
         # ./lib/neo4j/shared/callbacks.rb:39:in `create_model'
         # ./lib/neo4j/shared/persistence.rb:64:in `create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
         # ./lib/neo4j/active_node/persistence.rb:28:in `block in save'
         # ./lib/neo4j/active_node/persistence.rb:90:in `block in cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:89:in `cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:26:in `save'
         # ./lib/neo4j/shared/validations.rb:18:in `save'
         # ./lib/neo4j/active_node/persistence.rb:103:in `block in create'
         # ./lib/neo4j/active_node/persistence.rb:101:in `tap'
         # ./lib/neo4j/active_node/persistence.rb:101:in `create'
         # ./spec/e2e/label_spec.rb:87:in `block (5 levels) in <top (required)>'
         # ./spec/e2e/label_spec.rb:87:in `block (4 levels) in <top (required)>'
     # ./spec/e2e/label_spec.rb:87:in `block (4 levels) in <top (required)>'

Finished in 59.26 seconds
1015 examples, 3 failures, 4 pending
```

Is it safe to use the master branch? I ran tests on a 5.x version and they passed for me there. Also on neo4j community 2.3 if that helps.

Thanks!

### PR DESCRIPTION
**Pull request by venkatd**
When I ran the specs on my machine I was getting  an uninitialized error:

```
       uninitialized constant Neo4j::Core::CypherSession
```

Fixes #999 for just neo4j 2.2x. If I use neo4j 2.3 there are 3-4 failing tests.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/neo4jrb/neo4j/pull/1000" target="_blank">ReviewNinja

**Comment by subvertallchris** [comment]
Thanks for checking this out! I think this needs to be fixed in the `Neo4j-core` gem, not here. @cheerfulstoic?

**Comment by venkatd** [comment]
Does the require to be added to this file?
https://github.com/neo4jrb/neo4j-core/blob/master/lib/neo4j-core.rb

**Comment by subvertallchris** [comment]
That is where it'd be added but I want to be sure that this is supposed to be required at all. I don't think Brian wanted that class being used in this gem yet, so the solution might be to fix whatever forces its requirement.

**Comment by cheerfulstoic** [comment]
Whoops, I meant for that last comment in #999 to bbe on here.  Going to close this one as well as per that comment.

Congrats on being issue #1000!  Thanks for the help!

**Pull request closed without merging**
