### PR TITLE
Added #update_all method to ActiveNode and QueryProxy.

### PR DESCRIPTION
**Pull request by ProGM**
@cheerfulstoic 
I tried to implement #926 

Should this work also for `ActiveRel`?
I know you deprecated all query methods for `ActiveRel`, so I don't know if it could make sense.

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Awesome, thanks!  I'll look more later, but some quick feedback:

 * I don't remember if we cache the result of `count` on a query proxy chain, but if we do then the `expect().not_to change` wouldn't work.  Did you check that?
 * The `QueryProxyMethods` module gets mixed into `QueryProxy` so I wonder why `Model.update_all` is working.  Normally we can define a class method like `update_all` on `ActiveNode` and `QueryProxy` will take care of doing `method_missing` magic to delegate the method call from `QueryProxy` chains.

Regarding updating relationships, that's a really good question.  Perhaps we should define something like `update_all_rels` (which actually would be defined on `QueryProxy` and not `ActiveRel`, I think) so that you could call it to update the `rel_var`.  Come to think of it there is a variable that you should probably be using so that `Model.association(:var).update_all()` works because you can't use `n`.  `QueryProxy` objects have an abliity to find the current variable for the node and the relationship.

I need to run now, but this is great!  Thanks so much!

**Comment by ProGM** [comment]
Great!
* To be sure that the query is updating thing that shouldn't be updated... but maybe I can remove it.
* Check here, there's a `delegate :update_all, to: :all` https://github.com/neo4jrb/neo4j/pull/1113/files#diff-dfd59f2a8fc368af1d19efadf9411bb8R81

> Come to think of it there is a variable that you should probably be using so that Model.association(:var).update_all() works because you can't use n. QueryProxy objects have an abliity to find the current variable for the node and the relationship.

So I may replace `n` with "the current variable name" in the `update_all`, right? So this should be valid also for `ActiveNode`...

**Comment by ProGM** [comment]
News in the last commit:
* I implemented `person = Person.friends(:f).update_all_rels(friendship: 100)` :+1: 
* I moved all tests from `active_node_spec.rb` to `query_proxy_methods_spec.rb`... Because it makes more sense.
* I monkey patched a rubocop offense adding a `# rubocop:disable Metrics/ModuleLength`

**Comment by cheerfulstoic** [comment]
This is awesome and beautiful (with lots of tests), thanks so much! We might decide to move the `update_all` method into the `ActiveNode` space at some point to match with the existing `method_missing` behavior, but this works great for now.

Hopefully I can finish my other refactoring in the near future and we can get a release out with this in it!

**Comment by ProGM** [comment]
Great! :+1: Do you think you can close #926 ?

**Comment by cheerfulstoic** [comment]
We generally leave issues open until they're available in a rubygems gem, so I'll close it when we release.

Thanks!

**Pull request merged**
