### PR TITLE
fixes incorrect type when association type: false && model_class set

### LINKED ISSUE #929: When using `type` and `model_class` together, `type` isn't used
Example:

```ruby
has_many :out, :all_entities, model_class: :Entity, type: false
```

Reported by @leviwilson

### PR DESCRIPTION
**Pull request by subvertallchris**
Fixes #929

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
This is great, thanks!  I cherry-picked to 5.1.x and released as 5.1.2 (cc @leviwilson )

**Comment by subvertallchris** [comment]
Bah, I meant to put this into 5.1.x in the first place. Thanks for catching
that.

**Comment by cheerfulstoic** [comment]
No problem ;)  I figured it would be quicker for me to do it than to ask you to do it

**Comment by leviwilson** [comment]
Awesome, thanks guys!

**Pull request merged**
