### PR TITLE
Allow same name for property and scope

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Ran across this issue in the GraphGist portal app.  My code:

```ruby
class UseCase < GraphStarter::Asset
  property :name, type: String
  property :for_challenge, type: Boolean

  scope :for_challenge, -> { where(for_challenge: true) }

  has_many :in, :graph_gists, origin: :use_cases
end
```

Whenever I would try to use the `UseCase` model (or an association to it), I would get a "stack level to deep" message.  Tracked it down and it seems like we're creating an instance method for scopes, though I don't think we ever need an instance method for scopes, so I killed it.

@subvertallchris seem good?

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Gah, I think I branched from the wrong point.  This is supposed to go into 6.0.x but it looks like some of my changes from my other PR are there.  I can merge both in at once.  The only file that needs a look here is `scope.rb`

**Comment by subvertallchris** [comment]
Looks good to me. Any reason you can think of that it was like that in the
first place? Not saying that in an accusatory way, (I don't even know who
built that... Was it part of the original implementation?) I'm just curious.

**Comment by cheerfulstoic** [comment]
Looks like I refactored the code in 670a35305af68c5239525b3bda02272182d7c8b2 but it's been there since the implementation of scopes my @andreasronge in c14fec230405f78548b122702089f89547711eb5

**Comment by cheerfulstoic** [comment]
The original issue was #444 which has a link to the docs for scopes.  I don't think that the docs show a method on instances, so I think we're good

**Comment by cheerfulstoic** [comment]
Since this PR is conflicted I made the change manually to `6.0.x` and `master`

**Pull request closed without merging**
