### PR TITLE
When doing QueryProxy queries on models which are subclasses...

### PR DESCRIPTION
**Pull request by cheerfulstoic**
specify all labels in the `MATCH`

### CODE REVIEW

**Comment by subvertallchris** [comment]
I was thinking about this last night and now I'm not so sure about it. When doing `MATCH (u:User:GithubUser)`, wouldn't it match nodes with either label, not both labels?

**Comment by ikwattro** [comment]
Nope it will return nodes with both labels. The problem with such query is a bit performance when dealing with big databases, check section `avoid the need to match on multiple labels` here http://graphaware.com/neo4j/2015/01/16/neo4j-graph-model-design-labels-versus-indexed-properties.html

**Comment by subvertallchris** [comment]
Yeah, I double checked just after posting and noticed that. My bad. The stuff mentioned in that link under "Use well named relationship types to avoid some use of labels" was what I was talking about the other day, @cheerfulstoic.

**Comment by cheerfulstoic** [comment]
Gotcha.  It was actually @jexp who suggested I use multiple labels.  I actually re-worked neo4apis to fit that idea.  I wonder if making multiple labels more performant is on the radar

**Comment by cheerfulstoic** [comment]
Also, it just occurred to me, does this apply to neo4j 2.2?  One min, off to check ;p

**Comment by jexp** [comment]
The performance impact is not so bad, it is cheaper to check for a label than for a property

**Comment by cheerfulstoic** [comment]
Ah ha!  2.2 seem to help here!  I wrote a quick Ruby script ([code here](https://gist.github.com/cheerfulstoic/bae681a589c4dc172bad)) to get the number of DB hits for each query and the label order doesn't seem to matter in 2.2 (not that `User.login` isn't indexed here):

## `neo4j 2.1.7`

```
$ ruby profile_test.rb
MATCH (u:User) RETURN *: 8389
MATCH (u:User:GitHub) RETURN *: 8388
MATCH (u:User:StackOverflow) RETURN *: 8388
MATCH (u:User) WHERE u:GitHub RETURN *: 8388
MATCH (u:StackOverflow:User) RETURN *: 8646
MATCH (u:GitHub:User) RETURN *: 46574
MATCH (u:User) WHERE u.login = 'cheerfulstoic' RETURN *: 16776
MATCH (u:User:GitHub) WHERE u.login = 'cheerfulstoic' RETURN *: 25164
```

## `neo4j 2.2.0-M04`

```
$ ruby profile_test.rb
MATCH (u:User) RETURN *: 8389
MATCH (u:User:GitHub) RETURN *: 8388
MATCH (u:User:StackOverflow) RETURN *: 8388
MATCH (u:User) WHERE u:GitHub RETURN *: 8388
MATCH (u:StackOverflow:User) RETURN *: 8388
MATCH (u:GitHub:User) RETURN *: 8388
MATCH (u:User) WHERE u.login = 'cheerfulstoic' RETURN *: 16776
MATCH (u:User:GitHub) WHERE u.login = 'cheerfulstoic' RETURN *: 25164
```

**Comment by jexp** [comment]
2.2. uses a cost based planner, so whichever label has the lower cardinality in the database (is more selective) is used first and then the second label is checked against it.

**Pull request merged**
