### PR TITLE
Support ERB in 'neo4j.yml' config file

### PR DESCRIPTION
**Pull request by mrstif**
Support ERB in the `neo4j.yml` config file:

    development:
      url: http://localhost:7474
    production:
      url: <%= ENV['NEO4J_URL'] %>

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
I actually considered this, but I think the `railtie.rb` automatically looks for and prioritizes the `NEO4J_URL` environment variable.  Is that what you're experiencing?

**Comment by mrstif** [comment]
Sorry @cheerfulstoic ! This was a bad example... I didn't remember that that variable is actually the reserved one in the railtie... A proper example would be `<%= ENV['GRAPHSTORY_URL'] %>`

Just think it's a bit messy to scatter the configuration all around. It's just a matter of keeping it all in one place :)

**Comment by cheerfulstoic** [comment]
Right, good point.  Let's do it!

**Comment by mrstif** [comment]
Cheers @cheerfulstoic ! :D

**Pull request merged**
