### PR TITLE
fix association setting with node ids

### PR DESCRIPTION
**Pull request by subvertallchris**
@jacobwgillespie pointed out that unpersisted relationship setting wasn't working with ids. This should fix that.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Works for me - thanks!  :+1:

**Comment by subvertallchris** [comment]
Great! Can you wait for a general release of this or do you need a patch ASAP? I'm going out to lunch for real now but we can do a patch when I get back if you need it.

**Comment by jacobwgillespie** [comment]
Patch would be awesome if it's not too much trouble - thanks!

**Comment by subvertallchris** [comment]
Let me see if I can modify that query that clears out the old rel ids first...

**Pull request merged**
