### PR TITLE
Improve rails generators, added a migrator for 8.x.

### LINKED ISSUE #1252: Several issues with migrations
* [x] Migrations should print the performed queries, like active record does
* [x] Migrations should print the execution time
* [x] When making schema and data changes in the same migration, the error should suggest to set `disable_transactions!` in the migration file.
* [x] As an alternative: we might just run the migration itself inside the transaction and do a "rollback" outside of the transaction by checking to see if an error was raised and deleting the SchemaMigration node if so
* [x] When the previous error appears, `http` connection hangs instead of giving an error.
* [x] Schema-only migrations should not raise errors

About migrating from neo4j 7.x to 8.x
* [x] There should be a rails specific generator, to migrate everything at once
* [ ] The `neo4j:generate_schema_migration` should accept multiple parameters:
```
rake neo4j:generate_schema_migration[index,Desk,type,name,some,other]
```
Or also:
```
rake neo4j:generate_schema_migration[index:Desk:type:name,constraint:Desk:other]
```

### Runtime information:

Neo4j database version: 3.0.3
`neo4j` gem version: 8.0.0.alpha.1
`neo4j-core` gem version: 7.0.0.alpha.1

### PR DESCRIPTION
**Pull request by ProGM**
Fixes #1252 #1255 

This pull introduces/changes:
 * Model generator creates a migration as well
 * A generator to migrate all legacy model schema definitions at once

W.I.P.

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

**Comment by ProGM** [comment]
Tested on a rich rails project:
The migration task works quite good, but can't identify index defined by `enum`s

I think we need an `ensure_enum_defined!` or something like this.

**Comment by cheerfulstoic** [comment]
Don't we define enums at load time of the class?  Maybe we need reflection to see what enums are defined?

**Comment by ProGM** [comment]
Indeed I'm confused. I though enums where created on class definition, but in some way, you can't get them in the indexes list till you make a query. :\
Investigating...

**Comment by ProGM** [comment]
@cheerfulstoic I think I finished. ;)

**Comment by subvertallchris** [comment]
This is really great. 👍

**Comment by cheerfulstoic** [comment]
Seems great to me too!  Whats up with:

 * Making enum indexes warnings and not exceptions
 * #1261 (this might also be appropriate for back-porting to 7.1)

**Pull request merged**
