### PR TITLE
fixes #1017 by doing nothing on_match

### LINKED ISSUE #1017: `find_or_create` (uses merge) should not change anything on match
This:

```ruby
      def find_or_create(find_attributes, set_attributes = {})
        on_create_attributes = set_attributes.merge(on_create_props(find_attributes))
        on_match_attributes =  set_attributes.merge(on_match_props)
        neo4j_session.query.merge(n: {self.mapped_label_names => find_attributes})
          .on_create_set(n: on_create_attributes).on_match_set(n: on_match_attributes)
          .pluck(:n).first
      end
```

Should be this:

```ruby
      def find_or_create(find_attributes, set_attributes = {})
        on_create_attributes = set_attributes.merge(on_create_props(find_attributes))
        neo4j_session.query.merge(n: {self.mapped_label_names => find_attributes})
          .on_create_set(n: on_create_attributes)
          .pluck(:n).first
      end
```

### PR DESCRIPTION
**Pull request by leviwilson**
## Description
Fixes #1017 by doing nothing `on_match`.

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
I'm understanding this now.  I think we can consider this a bug and put it into 5.2.x.  What do you think @subvertallchris ?

**Comment by subvertallchris** [comment]
I think we can count this as a being fixed. My only hesitation is that
someone might have stumbled upon the weird behavior and started relying on
it, but I think that'd be a "shame-on-them" situation.

**Comment by subvertallchris** [comment]
I'm into merging this if all parties give :+1:

**Comment by cheerfulstoic** [comment]
Yeah, the combination of rarity of dependence and badness of the issue I think makes it worth a backport.

Since you're good with it I'll merge/cherry-pick

**Comment by cheerfulstoic** [comment]
I cherry-picked this into the 5.2.x branch so you can test it as `gem 'neo4j', github: 'neo4jrb/neo4j', branch: '5.2.x'` in your `Gemfile`.  Will release a patch gem soon

**Pull request merged**
