### PR TITLE
Added rel_order for ordering on relationships.

### PR DESCRIPTION
**Pull request by nrdobie**
This will allow you to order based on relationship properties easily rather than using the current solution in I came up with in #697.

### CODE REVIEW

**Comment by subvertallchris** [comment]
Awesome! Could you throw a test in and run `rubocop -a` to get it into compliance?

**Comment by nrdobie** [comment]
It looks like the issue with Rubocop is that with the additional function the class is now 247 lines long which exceeds the allowed 244 lines. To get compliance it looks like I'd have to either increase the limit, try to restructure the class to decrease the number of lines, or move some of the functionality of the QueryProxy class to a separate class.

I should be able to get some test written this evening.

**Comment by cheerfulstoic** [comment]
I've made some changes to `master` to reduce the line count.  I think it could use some more substantial refactoring, but this should help for now

**Comment by DavidChouinard** [comment]
Any update regarding merging this?

**Comment by subvertallchris** [comment]
Good question. @nrdobie, what say you?

**Comment by cheerfulstoic** [comment]
Closing in favor of #995 since so much has changed.  Thanks for the basis of this @nrdobie !

**Comment by cheerfulstoic** [comment]
Released as 6.0.0.alpha.8

**Pull request closed without merging**
