### PR TITLE
Rails 5 beta support

### PR DESCRIPTION
**Pull request by subvertallchris**
We'll need to do a major release to support this but in case anyone is looking to try Rails 5, the `rails5` branch updates its dependencies appropriately.

```
gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'rails5'
```

Aside from the dependencies, our big breaking change here is removal of `to_xml`.

Rails 5 has a lot of changes under the hood. It would be nice to look at their changes to ActiveModel and see if there's anything that we can take advantage of. It also drops support for Ruby < 2.2.x, so we should think about what, if anything, we want to do about this.

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
I'm not too familiar with the new Attributes API in ActiveRecord yet, but it sounds nice.  Heard about it on this Ruby Rogues episode: https://devchat.tv/ruby-rogues/222-rr-rails-5-with-sean-griffin

**Comment by subvertallchris** [comment]
Yeah, I looked over that a little. We _might_ be able to use it to replace `ActiveAttr` entirely. I plan on diving into it over the long weekend.

**Comment by agustinvinao** [comment]
How is this going? we are in beta3 for Rails5 and it should be very nice if we can use it with neo4j. How can I help here?

**Comment by cheerfulstoic** [comment]
Hey @agustinvinao !

So @subvertallchris is more familiar with the Rails 5 support, but he just got married and he'll be gone for a week or so.  I updated this branch from `master` not too long ago (see https://github.com/neo4jrb/neo4j/issues/981 ) and got some feedback from @disastrous-charly that it was working for him.

You could definitely help by trying out the branch and letting us know if anything doesn't work for you!  We generally hang out here:

https://gitter.im/neo4jrb/neo4j

I'll also be a bit busy starting Wednesday because I'll be traveling as well, but I'll try to respond if you have any issues.  If you want to try out the branch you can put this in your `Gemfile`:

```ruby
gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'rails5'
```

Thanks!

**Comment by agustinvinao** [comment]
Hi @cheerfulstoic,

I've created a project with edge rails5 code and the rails5 branch for neo4j, many things doesn't work.

I'll try to put some time to see what I can fix and send any comment or hag out with you or the rest of the devs here.

I'm using neo4j in a rails4 project but I want to move to rails5 as soon as I can. All of us are a bit busy but I'll try to put some time here.

**Comment by cheerfulstoic** [comment]
Awesome, any time that you can spare would be fantastic.  I haven't actually tried it with Rails 5 but I'll do that too so that I can help ;)

**Comment by subvertallchris** [comment]
Hi guys, just back from my trip and catching up on things.

As you probably saw from the meat of this PR, it only took some slight dependency changes to get our tests passing, but that might not be the whole story. When I have some time this week, I'll update this branch to the latest Rails 5 release and will fix any failing tests that pop up. If you get to it sooner, we'd love to see that, of course.

**Pull request closed without merging**
